apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: rabbit-consumer-1
  namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: rabbit-samples
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  serviceClaims:
    - name: rmq
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: rmq-1
  source:
    git:
      url: https://github.com/sumantrana/scs-rabbitmq-consumer.git
      ref:
        branch: main